apiVersion: apps/v1
kind: Deployment
metadata: { name: gitops-demo }
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: gitops-demo } }
  template:
    metadata: { labels: { app: gitops-demo } }
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports: [{ containerPort: 8080 }]
        readinessProbe: { httpGet: { path: /health, port: 8080 } }
        livenessProbe: { httpGet: { path: /health, port: 8080 } }
