apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: gitops-demo, namespace: argocd }
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/aws-k8s-gitops-progressive-delivery.git
    targetRevision: main
    path: helm/application
  destination: { server: https://kubernetes.default.svc, namespace: gitops-demo }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
